name: Deploy React App to Hostinger

on:
  push:
    branches:
      - main # Trigger the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16 # Use the Node.js version compatible with your project

    # Step 3: Install dependencies and build the app
    - name: Install Dependencies and Build
      run: |
        cd frontend
        npm install
        npm run build # Builds your React app into the `build` folder

    # Step 4: Deploy files to Hostinger via FTP
    - name: Deploy to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftp # Ensure the protocol is FTP
        port: 21 # Port for FTP (default)
        local-dir: frontend/build/ # Path to the build folder inside your repository
        server-dir: /public_html/alumnitracer # Target folder on Hostinger
